# Generated by Django 6.1 on 2026-08-21 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(help_text="e.g. 'Mother', 'Father', 'Uncle', 'Legal Guardian'", max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='smsApp.school')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardians',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=15)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned')], db_index=True, default='ACTIVE', max_length=15)),
                ('date_hired', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='smsApp.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='smsApp.school')),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['STAFF_ADMIN', 'ACADEMIC_ADMIN', 'FINANCE_ADMIN', 'TEACHER', 'EXAM_OFFICER', 'CLASS_TEACHER', 'DEPARTMENT_HEAD', 'ACCOUNTANT', 'LIBRARIAN']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('DEGREE', 'Degree'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('LICENSE', 'Professional License'), ('OTHER', 'Other')], max_length=15)),
                ('title', models.CharField(help_text="e.g. 'B.Ed Mathematics'", max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('year_obtained', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='staff/qualifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='smsApp.staff')),
            ],
            options={
                'db_table': 'staff_qualifications',
                'ordering': ['-year_obtained'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=30)),
                ('admission_date', models.DateField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('national_id', models.CharField(blank=True, help_text='Birth certificate no. or national ID.', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred'), ('DEFERRED', 'Deferred'), ('WITHDRAWN', 'Withdrawn'), ('EXPELLED', 'Expelled'), ('ALUMNI', 'Alumni')], db_index=True, default='ACTIVE', max_length=15)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('medical_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='smsApp.class')),
                ('current_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='smsApp.stream')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='smsApp.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='smsApp.school')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=True)),
                ('is_billing_contact', models.BooleanField(default=False, help_text='Who fee invoices/statements are addressed to (Finance module, Phase 19).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsApp.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsApp.student')),
            ],
            options={
                'db_table': 'student_guardians',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(related_name='students', through='smsApp.StudentGuardian', to='smsApp.guardian'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('school', 'staff_id'), name='uniq_staff_id_per_school'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='uniq_student_guardian_pair'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'admission_number'), name='uniq_admission_number_per_school'),
        ),
    ]
