# Generated by Django 6.1 on 2026-08-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0003_auditlog_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject_type', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective')], default='CORE', max_length=10)),
                ('credit_hours', models.DecimalField(blank=True, decimal_places=1, help_text='University-style credit hours. Leave blank for school-style subjects.', max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='smsApp.department')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='smsApp.subject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='smsApp.school')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='smsApp.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='smsApp.subject')),
            ],
            options={
                'db_table': 'class_subjects',
                'ordering': ['class_group', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='smsApp.classsubject')),
                ('teacher', models.ForeignKey(limit_choices_to={'employment_status': 'ACTIVE'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='smsApp.staff')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='smsApp.term')),
            ],
            options={
                'db_table': 'teaching_assignments',
                'ordering': ['term', 'class_subject'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed')], db_index=True, default='ENROLLED', max_length=10)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('dropped_on', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='smsApp.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='smsApp.classsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='smsApp.student')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrolled_on'],
                'constraints': [models.UniqueConstraint(fields=('student', 'class_subject', 'academic_year'), name='uniq_enrollment_per_student_subject_year')],
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uniq_subject_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('class_group', 'subject'), name='uniq_subject_per_class'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('class_subject', 'term'), name='uniq_teacher_per_class_subject_term'),
        ),
    ]
