# Generated by Django 6.1 on 2026-08-22 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0005_attendancesession_attendancerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, help_text='Marks this component is scored out of before weighting is applied.', max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'assessment_components',
                'ordering': ['structure', 'order'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='enable_position_ranking',
            field=models.BooleanField(default=True, help_text='Spec §13: some schools choose not to rank students. Result-processing/report-book views must check this flag before showing or computing positions.'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'CAT 1 - Algebra'", max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Marks visible to students/parents only once published (spec §14 Result Processing Workflow governs this fully).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='smsApp.classsubject')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to='smsApp.staff')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='smsApp.term')),
                ('component', models.ForeignKey(help_text="Defines this assessment's weight and max marks.", on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='smsApp.assessmentcomponent')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Standard Term Structure'", max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_structures', to='smsApp.school')),
                ('subject', models.ForeignKey(blank=True, help_text='Leave blank to apply this structure to all subjects in the term.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_structures', to='smsApp.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_structures', to='smsApp.term')),
            ],
            options={
                'db_table': 'assessment_structures',
                'ordering': ['term', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='smsApp.assessmentstructure'),
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'CAT', 'Midterm', 'Final Exam'", max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='smsApp.school')),
            ],
            options={
                'db_table': 'assessment_types',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_components', to='smsApp.assessmenttype'),
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Standard 8-4-4 Grading'", max_length=150)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_schemes', to='smsApp.school')),
            ],
            options={
                'db_table': 'grading_schemes',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(help_text="e.g. 'A', 'B+', 'Pass'", max_length=10)),
                ('grade_point', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('remark', models.CharField(blank=True, help_text="e.g. 'Excellent'", max_length=100)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='smsApp.gradingscheme')),
            ],
            options={
                'db_table': 'grade_bands',
                'ordering': ['scheme', '-min_mark'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='smsApp.assessment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='smsApp.student')),
            ],
            options={
                'db_table': 'assessment_marks',
                'ordering': ['assessment', 'student'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'student'), name='uniq_mark_per_assessment_student'), models.CheckConstraint(condition=models.Q(('marks_obtained__gte', 0)), name='marks_obtained_non_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmenttype',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uniq_assessment_type_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcomponent',
            constraint=models.UniqueConstraint(fields=('structure', 'assessment_type'), name='uniq_assessment_type_per_structure'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('weight_percentage__gte', 0), ('weight_percentage__lte', 100)), name='component_weight_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(fields=('scheme', 'grade'), name='uniq_grade_per_scheme'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.CheckConstraint(condition=models.Q(('max_mark__gte', models.F('min_mark'))), name='grade_band_max_gte_min'),
        ),
    ]
