# Generated by Django 6.1 on 2026-08-22 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0006_assessmentcomponent_school_enable_position_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Department/Class Teacher review step (spec §14).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Academic Admin verification step (spec §14).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Marks visible to students/parents. Set automatically when workflow_status reaches PUBLISHED — do not set this directly, use services.transition_assessment_workflow().'),
        ),
        migrations.CreateModel(
            name='ResultAmendmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('original_mark', models.DecimalField(decimal_places=2, help_text='Snapshot of the mark at request time, independent of whatever the mark is by the time this is reviewed.', max_digits=6)),
                ('proposed_mark', models.DecimalField(decimal_places=2, max_digits=6)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.CharField(blank=True, max_length=255)),
                ('assessment_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_requests', to='smsApp.assessmentmark')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendment_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendment_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'result_amendment_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
