# Generated by Django 6.1 on 2026-08-23 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0007_assessment_approved_at_assessment_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Standard Term Report'", max_length=150)),
                ('template_key', models.CharField(choices=[('DEFAULT', 'Default')], default='DEFAULT', max_length=20)),
                ('show_position', models.BooleanField(default=True, help_text='Also requires School.enable_position_ranking to be True.')),
                ('show_gpa', models.BooleanField(default=False)),
                ('show_attendance', models.BooleanField(default=True)),
                ('footer_text', models.CharField(blank=True, help_text='e.g. a motto or accreditation line shown at the report footer.', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='smsApp.school')),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('principal_comment', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/cards/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False, help_text="Once finalized, regenerating should create a new PDF revision rather than silently overwrite (spec §37/§38 'never silently change'). Enforcement lands with the generation view.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards_generated', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='smsApp.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='smsApp.term')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='smsApp.reporttemplate')),
            ],
            options={
                'db_table': 'report_cards',
                'ordering': ['-generated_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'term', 'template'), name='uniq_report_card_per_student_term_template')],
            },
        ),
    ]
