# Generated by Django 6.1 on 2026-08-23 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0008_reporttemplate_reportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('academic_status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred'), ('DEFERRED', 'Deferred'), ('WITHDRAWN', 'Withdrawn'), ('EXPELLED', 'Expelled'), ('ALUMNI', 'Alumni')], max_length=15)),
                ('graduation_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('GRADUATED', 'Graduated'), ('NOT_GRADUATED', 'Not Graduated')], default='IN_PROGRESS', max_length=15)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text="Most recent term/year's grade-point average.", max_digits=4, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative GPA across every entry on this transcript.', max_digits=4, null=True)),
                ('verification_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 of the assembled transcript data at generation time, for tamper-evidence alongside verification_code.', max_length=64)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='transcripts/')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripts_generated', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='smsApp.student')),
            ],
            options={
                'db_table': 'transcripts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('academic_year_label', models.CharField(max_length=20)),
                ('term_label', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('credit_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_entries', to='smsApp.subject')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='smsApp.transcript')),
            ],
            options={
                'db_table': 'transcript_entries',
                'ordering': ['academic_year_label', 'term_label', 'subject_name'],
            },
        ),
    ]
