# Generated by Django 6.1 on 2026-08-24 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0011_author_publisher_bookcategory_book_bookcopy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_break', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='smsApp.school')),
            ],
            options={
                'db_table': 'periods',
                'ordering': ['school', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('LIBRARY', 'Library'), ('HALL', 'Hall'), ('OTHER', 'Other')], default='CLASSROOM', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 = not tracked')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='smsApp.school')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='smsApp.class')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='smsApp.period')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='smsApp.room')),
                ('teacher', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='smsApp.staff')),
                ('teaching_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='smsApp.teachingassignment')),
                ('term', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='smsApp.term')),
            ],
            options={
                'db_table': 'timetable_slots',
                'ordering': ['term', 'day_of_week', 'period'],
            },
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_period_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_room_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('teacher', 'term', 'day_of_week', 'period'), name='uniq_teacher_timetable_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'term', 'day_of_week', 'period'), name='uniq_room_timetable_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('class_group', 'term', 'day_of_week', 'period'), name='uniq_class_timetable_slot'),
        ),
    ]
