# Generated by Django 6.1 on 2026-08-31 06:09

import smsApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0014_leaverequest_staffattendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lms/assignment_resources/', validators=[smsApp.validators.MaxFileSizeValidator(200), smsApp.validators.validate_course_material_content]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='lms/submissions/', validators=[smsApp.validators.MaxFileSizeValidator(25), smsApp.validators.validate_document_content]),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='library/covers/', validators=[smsApp.validators.MaxFileSizeValidator(5), smsApp.validators.validate_image_content]),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lms/materials/', validators=[smsApp.validators.MaxFileSizeValidator(200), smsApp.validators.validate_course_material_content]),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='finance/receipts/', validators=[smsApp.validators.MaxFileSizeValidator(20), smsApp.validators.validate_pdf_content]),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/cards/', validators=[smsApp.validators.MaxFileSizeValidator(20), smsApp.validators.validate_pdf_content]),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school/logos/', validators=[smsApp.validators.MaxFileSizeValidator(5), smsApp.validators.validate_image_content]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/', validators=[smsApp.validators.MaxFileSizeValidator(5), smsApp.validators.validate_image_content]),
        ),
        migrations.AlterField(
            model_name='staffqualification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='staff/qualifications/', validators=[smsApp.validators.MaxFileSizeValidator(10), smsApp.validators.validate_document_content]),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/', validators=[smsApp.validators.MaxFileSizeValidator(5), smsApp.validators.validate_image_content]),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/', validators=[smsApp.validators.MaxFileSizeValidator(20), smsApp.validators.validate_pdf_content]),
        ),
    ]
