# Generated by Django 6.1 on 2026-09-08 10:12

import smsApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0015_alter_assignmentresource_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='lms/assessment_questions/', validators=[smsApp.validators.MaxFileSizeValidator(5), smsApp.validators.validate_course_material_content]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='submission_format',
            field=models.CharField(choices=[('TEXT_ENTRY', 'Type answers'), ('FILE_UPLOAD', 'Upload document'), ('BOTH', 'Type answers or upload document')], default='TEXT_ENTRY', max_length=15),
        ),
        migrations.AddField(
            model_name='quiz',
            name='task_category',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('CAT', 'CAT'), ('EXAM', 'Exam')], db_index=True, default='QUIZ', max_length=10),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='lms/quiz_submissions/', validators=[smsApp.validators.MaxFileSizeValidator(25), smsApp.validators.validate_document_content]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RESULT_PUBLISHED', 'Result Published'), ('REPORT_AVAILABLE', 'Report Available'), ('PAYMENT_RECEIVED', 'Payment Received'), ('ASSIGNMENT_DEADLINE', 'Assignment Deadline'), ('ANNOUNCEMENT', 'Announcement'), ('ATTENDANCE', 'Attendance'), ('TASK_ADDED', 'Task Added'), ('SUBMISSION_RECEIVED', 'Submission Received'), ('OTHER', 'Other')], db_index=True, max_length=25),
        ),
    ]
