# Generated by Django 6.1 on 2026-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0016_quiz_question_file_quiz_submission_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='overdue_reopened',
            field=models.BooleanField(default=False, help_text='Teacher has reopened this overdue assignment for eligible students.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='overdue_reopened',
            field=models.BooleanField(default=False, help_text='Teacher has reopened this overdue task for eligible students.'),
        ),
    ]
