# Generated by Django 6.1 on 2026-09-08 11:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0017_assignment_max_attempts_assignment_overdue_reopened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Task score is normalized against this maximum; defaults to 100.', max_digits=6),
        ),
    ]
