# Generated by Django 6.1 on 2026-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0018_quiz_max_marks'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_recipient_read_idx'),
        ),
    ]
